#http-method
POST

#url
http://localhost:8080/employee

#http-header
@Content-Type: application/json

#request body
{
"name": "Swayam",
"age" : "26"
}




%%%

# Duration: 485 ms
# URL: http://localhost:8080/employee

# HTTP/1.1 200

@Content-Type: application/json
@Transfer-Encoding: chunked
@Date: Mon, 20 Jul 2020 05:07:33 GMT
@Keep-Alive: timeout=60
@Connection: keep-alive

{
  "id": 1,
  "name": "Swayam",
  "age": 26
}